const STATUS = {
    en: {},
    ru: {
        'Not configured': 'Не настроено',
        Connected: 'Подключено',
        'Connected (webhook not set)': 'Подключено, webhook не задан',
        Disabled: 'Выключено',
        Configured: 'Настроено',
        Partial: 'Частично',
        Ready: 'Готово',
        Error: 'Ошибка',
        'Webhook set': 'Webhook задан',
        'Token saved': 'Токен сохранён',
        'API key required': 'Нужен API-ключ',
        'Gemini not configured': 'Gemini не настроен',
        'Calendar and Gmail permission required.': 'Нужны разрешения Calendar и Gmail.',
        'Calendar permission required.': 'Нужно разрешение Calendar.',
        'Gmail permission required.': 'Нужно разрешение Gmail.',
        'Access token will refresh when needed.': 'Токен доступа обновится при необходимости.',
        'Reconnect recommended.': 'Рекомендуется переподключить.',
        'Reconnect required.': 'Нужно переподключить.',
        'Credentials are missing. Reconnect required.': 'Нет учётных данных. Нужно переподключить.',
        'Credentials are stored encrypted.': 'Учётные данные хранятся в зашифрованном виде.',
        Identity: 'Вход',
        connected: 'подключено',
        disconnected: 'не подключено',
        enabled: 'включено',
        permission_required: 'нужно разрешение',
        not_enabled: 'не включено',
        healthy: 'в порядке',
        refreshable: 'обновится',
        missing: 'нет данных',
        needs_reconnect: 'нужно переподключить',
        degraded: 'с ошибками',
        disabled: 'выключено',
    },
    uk: {
        'Not configured': 'Не налаштовано',
        Connected: 'Підключено',
        'Connected (webhook not set)': 'Підключено, webhook не задано',
        Disabled: 'Вимкнено',
        Configured: 'Налаштовано',
        Partial: 'Частково',
        Ready: 'Готово',
        Error: 'Помилка',
        'Webhook set': 'Webhook задано',
        'Token saved': 'Токен збережено',
        'API key required': 'Потрібен API-ключ',
        'Gemini not configured': 'Gemini не налаштовано',
        'Calendar and Gmail permission required.': 'Потрібні дозволи Calendar і Gmail.',
        'Calendar permission required.': 'Потрібен дозвіл Calendar.',
        'Gmail permission required.': 'Потрібен дозвіл Gmail.',
        'Access token will refresh when needed.': 'Токен доступу оновиться за потреби.',
        'Reconnect recommended.': 'Рекомендовано перепідключити.',
        'Reconnect required.': 'Потрібно перепідключити.',
        'Credentials are missing. Reconnect required.': 'Немає облікових даних. Потрібно перепідключити.',
        'Credentials are stored encrypted.': 'Облікові дані зберігаються зашифрованими.',
        Identity: 'Вхід',
        connected: 'підключено',
        disconnected: 'не підключено',
        enabled: 'увімкнено',
        permission_required: 'потрібен дозвіл',
        not_enabled: 'не увімкнено',
        healthy: 'гаразд',
        refreshable: 'оновиться',
        missing: 'немає даних',
        needs_reconnect: 'потрібно перепідключити',
        degraded: 'з помилками',
        disabled: 'вимкнено',
    },
};

export function translateKnown(locale, value) {
    if (value == null || value === '') {
        return value;
    }

    const table = STATUS[locale] ?? STATUS.en;

    return table[value] ?? value;
}
