export const SETTINGS_TABS = ['overview', 'ai', 'telegram', 'google', 'zoom', 'voice', 'web-research', 'activity'];

const COPY = {
    en: {
        pageTitle: 'Settings',
        overviewIntro:
            'Every connection in one place. Green means it works, amber means setup is unfinished, grey means it is switched off. Open a card to change its settings.',
        summaryWorking: 'connections working',
        open: 'Open',
        notConfigured: 'Not configured',

        groupAi: 'AI',
        groupChannels: 'Channels',
        groupSources: 'Data sources',
        groupAbilities: 'Abilities',
        groupDiagnostics: 'Diagnostics',

        tabOverview: 'Overview',
        tabAi: 'AI models',
        tabTelegram: 'Telegram',
        tabGoogle: 'Google',
        tabZoom: 'Zoom',
        tabVoice: 'Voice',
        tabWebResearch: 'Web research',
        tabActivity: 'Activity log',

        hintAi: 'Provider keys and the three AI configurations that run conversations.',
        hintTelegram: 'Bot token, webhook, and monitored groups.',
        hintGoogle: 'OAuth client, connected accounts, Gmail and Calendar.',
        hintZoom: 'Zoom app credentials and meeting transcripts.',
        hintVoice: 'Speech recognition and voice replies. This is not the conversation AI.',
        hintWebResearch: 'Search provider, credentials, and research limits.',
        hintActivity: 'Recent tool runs with duration and errors.',

        stateReady: 'Working',
        stateAttention: 'Finish setup',
        stateError: 'Error',
        stateOff: 'Not configured',
        stateInfo: 'Log',

        rowKeys: 'Provider keys',
        rowConfigurations: 'Configurations on',
        rowToken: 'Bot token',
        rowWebhook: 'Webhook',
        rowGroups: 'Monitored groups',
        rowOauthClient: 'OAuth client',
        rowAccounts: 'Connected accounts',
        rowGmail: 'Gmail',
        rowCalendar: 'Calendar',
        rowAccountStatus: 'Account',
        rowWebhookSecret: 'Webhook secret',
        rowStt: 'Speech to text',
        rowTts: 'Voice replies',
        rowElevenLabs: 'ElevenLabs key',
        rowSearchProvider: 'Search provider',
        rowAvailableToAssistant: 'Available to assistant',
        rowRecentRuns: 'Recent runs',

        valueSet: 'Saved',
        valueMissing: 'Missing',
        valueOn: 'On',
        valueOff: 'Off',
        valueNone: 'Not selected',

        aiNoKeys: 'No provider key saved yet',
        aiNoModel: 'Key saved, model not selected yet',
        roleLabels: {},

        oauthClient: 'OAuth client',
        account: 'Account',
        scopes: 'Scopes',
        connectedAt: 'Connected',
        tokenHealth: 'Token health',
        connect: 'Connect Google',
        reconnect: 'Reconnect',
        disconnect: 'Disconnect',
        enableCalendar: 'Enable Calendar',
        enableGmail: 'Enable Gmail',
        googleAccounts: 'Google accounts',
        addGoogle: 'Add Google account',
        noGoogleAccounts: 'No Google accounts yet.',
        noGmail: 'No Gmail',
        noCalendar: 'No Calendar',
        lastSync: 'Last activity',
        test: 'Test',
        enable: 'Enable',
        disable: 'Disable',
        disconnectConfirm: 'Connected source data may be removed. Confirmed business records are preserved.',
        telegramGroups: 'Telegram groups',
        monitoring: 'monitoring',
    },
    ru: {
        pageTitle: 'Настройки',
        overviewIntro:
            'Все подключения в одном месте. Зелёный — работает, янтарный — настройка не завершена, серый — выключено. Откройте карточку, чтобы изменить настройки.',
        summaryWorking: 'подключений работает',
        open: 'Открыть',
        notConfigured: 'Не настроено',

        groupAi: 'AI',
        groupChannels: 'Каналы',
        groupSources: 'Источники данных',
        groupAbilities: 'Возможности',
        groupDiagnostics: 'Диагностика',

        tabOverview: 'Обзор',
        tabAi: 'Модели AI',
        tabTelegram: 'Telegram',
        tabGoogle: 'Google',
        tabZoom: 'Zoom',
        tabVoice: 'Голос',
        tabWebResearch: 'Веб-поиск',
        tabActivity: 'Журнал',

        hintAi: 'Ключи провайдеров и три конфигурации AI, которые ведут разговоры.',
        hintTelegram: 'Токен бота, webhook и группы под наблюдением.',
        hintGoogle: 'OAuth-клиент, подключённые аккаунты, Gmail и Calendar.',
        hintZoom: 'Учётные данные Zoom и транскрипты встреч.',
        hintVoice: 'Распознавание речи и голосовые ответы. Это не разговорный AI.',
        hintWebResearch: 'Провайдер поиска, ключи и лимиты исследований.',
        hintActivity: 'Недавние выполнения инструментов: время, длительность, ошибки.',

        stateReady: 'Работает',
        stateAttention: 'Нужно завершить',
        stateError: 'Ошибка',
        stateOff: 'Не настроено',
        stateInfo: 'Журнал',

        rowKeys: 'Ключи провайдеров',
        rowConfigurations: 'Включено конфигураций',
        rowToken: 'Токен бота',
        rowWebhook: 'Webhook',
        rowGroups: 'Групп под наблюдением',
        rowOauthClient: 'OAuth-клиент',
        rowAccounts: 'Подключённых аккаунтов',
        rowGmail: 'Gmail',
        rowCalendar: 'Calendar',
        rowAccountStatus: 'Аккаунт',
        rowWebhookSecret: 'Секрет webhook',
        rowStt: 'Распознавание речи',
        rowTts: 'Голосовые ответы',
        rowElevenLabs: 'Ключ ElevenLabs',
        rowSearchProvider: 'Провайдер поиска',
        rowAvailableToAssistant: 'Доступно ассистенту',
        rowRecentRuns: 'Недавних выполнений',

        valueSet: 'Сохранён',
        valueMissing: 'Нет',
        valueOn: 'Включено',
        valueOff: 'Выключено',
        valueNone: 'Не выбрано',

        aiNoKeys: 'Ключ провайдера ещё не сохранён',
        aiNoModel: 'Ключ сохранён, модель ещё не выбрана',
        roleLabels: {
            'Owner Conversation AI': 'Разговор владельца',
            'Owner Analysis AI': 'Анализ владельца',
            'Default User Conversation AI': 'Разговор пользователя',
        },

        oauthClient: 'OAuth-клиент',
        account: 'Аккаунт',
        scopes: 'Доступы',
        connectedAt: 'Подключено',
        tokenHealth: 'Состояние токена',
        connect: 'Подключить Google',
        reconnect: 'Переподключить',
        disconnect: 'Отключить',
        enableCalendar: 'Включить Calendar',
        enableGmail: 'Включить Gmail',
        googleAccounts: 'Google-аккаунты',
        addGoogle: 'Добавить Google-аккаунт',
        noGoogleAccounts: 'Google-аккаунтов пока нет.',
        noGmail: 'Gmail не подключён',
        noCalendar: 'Calendar не подключён',
        lastSync: 'Последняя активность',
        test: 'Проверить',
        enable: 'Включить',
        disable: 'Отключить',
        disconnectConfirm: 'Данные подключения могут быть удалены. Подтверждённые бизнес-записи сохраняются.',
        telegramGroups: 'Группы Telegram',
        monitoring: 'мониторинг',
    },
    uk: {
        pageTitle: 'Налаштування',
        overviewIntro:
            'Усі підключення в одному місці. Зелений — працює, бурштиновий — налаштування не завершено, сірий — вимкнено. Відкрийте картку, щоб змінити налаштування.',
        summaryWorking: 'підключень працює',
        open: 'Відкрити',
        notConfigured: 'Не налаштовано',

        groupAi: 'AI',
        groupChannels: 'Канали',
        groupSources: 'Джерела даних',
        groupAbilities: 'Можливості',
        groupDiagnostics: 'Діагностика',

        tabOverview: 'Огляд',
        tabAi: 'Моделі AI',
        tabTelegram: 'Telegram',
        tabGoogle: 'Google',
        tabZoom: 'Zoom',
        tabVoice: 'Голос',
        tabWebResearch: 'Веб-пошук',
        tabActivity: 'Журнал',

        hintAi: 'Ключі провайдерів і три конфігурації AI, які ведуть розмови.',
        hintTelegram: 'Токен бота, webhook і групи під наглядом.',
        hintGoogle: 'OAuth-клієнт, підключені акаунти, Gmail і Calendar.',
        hintZoom: 'Облікові дані Zoom і транскрипти зустрічей.',
        hintVoice: 'Розпізнавання мовлення та голосові відповіді. Це не розмовний AI.',
        hintWebResearch: 'Провайдер пошуку, ключі та ліміти досліджень.',
        hintActivity: 'Недавні виконання інструментів: час, тривалість, помилки.',

        stateReady: 'Працює',
        stateAttention: 'Треба завершити',
        stateError: 'Помилка',
        stateOff: 'Не налаштовано',
        stateInfo: 'Журнал',

        rowKeys: 'Ключі провайдерів',
        rowConfigurations: 'Увімкнено конфігурацій',
        rowToken: 'Токен бота',
        rowWebhook: 'Webhook',
        rowGroups: 'Груп під наглядом',
        rowOauthClient: 'OAuth-клієнт',
        rowAccounts: 'Підключених акаунтів',
        rowGmail: 'Gmail',
        rowCalendar: 'Calendar',
        rowAccountStatus: 'Акаунт',
        rowWebhookSecret: 'Секрет webhook',
        rowStt: 'Розпізнавання мовлення',
        rowTts: 'Голосові відповіді',
        rowElevenLabs: 'Ключ ElevenLabs',
        rowSearchProvider: 'Провайдер пошуку',
        rowAvailableToAssistant: 'Доступно асистенту',
        rowRecentRuns: 'Недавніх виконань',

        valueSet: 'Збережено',
        valueMissing: 'Немає',
        valueOn: 'Увімкнено',
        valueOff: 'Вимкнено',
        valueNone: 'Не обрано',

        aiNoKeys: 'Ключ провайдера ще не збережено',
        aiNoModel: 'Ключ збережено, модель ще не обрана',
        roleLabels: {
            'Owner Conversation AI': 'Розмова власника',
            'Owner Analysis AI': 'Аналіз власника',
            'Default User Conversation AI': 'Розмова користувача',
        },

        oauthClient: 'OAuth-клієнт',
        account: 'Акаунт',
        scopes: 'Доступи',
        connectedAt: 'Підключено',
        tokenHealth: 'Стан токена',
        connect: 'Підключити Google',
        reconnect: 'Перепідключити',
        disconnect: 'Відключити',
        enableCalendar: 'Увімкнути Calendar',
        enableGmail: 'Увімкнути Gmail',
        googleAccounts: 'Google-акаунти',
        addGoogle: 'Додати Google-акаунт',
        noGoogleAccounts: 'Google-акаунтів поки немає.',
        noGmail: 'Gmail не підключено',
        noCalendar: 'Calendar не підключено',
        lastSync: 'Остання активність',
        test: 'Перевірити',
        enable: 'Увімкнути',
        disable: 'Вимкнути',
        disconnectConfirm: 'Дані підключення можуть бути видалені. Підтверджені бізнес-записи зберігаються.',
        telegramGroups: 'Групи Telegram',
        monitoring: 'моніторинг',
    },
};

export function settingsCopy(locale) {
    return COPY[locale] ?? COPY.en;
}
